function R = steadystate_calibration(x0,P)

omegal  = x0(1);
omegab  = x0(2);
K       = x0(3);
C       = x0(4);
D       = x0(5);
M       = x0(6);
DDC     = x0(7);
Omega   = x0(8);
eta_DC  = x0(9);
vartheta= x0(10);
eta_M   = x0(11);
mudist  = x0(12);
sigdist = x0(13);
psi     = x0(14);
phi     = x0(15);
Bgcbbar = x0(16);

f = model(x0,P);

L = f(1);
Rd = f(2);
I = f(3);
Ra = f(4);
Rb = f(5);
Rl = f(6);
Rk = f(7);
W = f(8);
H = f(9);
Y = f(10);
Bgcb = f(11);
Bg = f(12);
N = f(13);
Phib = f(14);
Phil = f(15);
Gammab = f(16);
Gammal = f(17);
varphi = f(18);
Bcb = f(19);
Rdf = f(20);
Rlf = f(21);
Rdc = f(22);
Rcb = f(23);
Rg = f(24);
Qg = f(25);
tassets = f(26);
condexpwb = f(27);
condexpwl = f(28);
Fomegab = f(29);
Fomegal = f(30);
condexpwlb = f(31);


R(1) = N - (P.varsigma*(Ra*Omega*K-Rb*Phib+Rl*Phil+Rg*Bg-Rd*D-Rcb*Bcb));
R(2) = W - H^P.kappa/(C)^-P.gamma;
R(3) = Y - C - I;
R(4) = Omega - (phi*(1-Fomegab)*condexpwb + (N+D)/((1-psi)*N)*(Fomegab-Fomegal)*condexpwlb)/(phi*(1-Fomegab)+(N+D)/((1-psi)*N)*(Fomegab-Fomegal));
R(5) = (1 - vartheta*(1/L)/(C^-P.gamma)*(eta_M)*(L/(M))^(1/P.varepsilon)) - P.beta;
R(6) = (1 - vartheta*(1/L)/(C^-P.gamma)*(eta_DC)*(L/(DDC))^(1/P.varepsilon)) - P.beta*P.Rdc;
R(7) = Rl-Rlf+(1-Gammal*(1-varphi))*P.chi;
R(8) = D + N + Bcb + Phib*(1-Gammab) - K - Bg - Phil*(1-Gammal);
R(9) = Rdf - P.Rdf_target;                  % Deposit facility rate
R(10) = M/Y/4 - P.M_target;                 % Banknotes as % of GDP
R(11) = Omega - 1;                          % Agg. TFP
R(12) = Phib*Gammab/tassets - P.IB_target;  % Interbank assets
R(13) = Bcb/tassets - 0;                    % TLTRO as % of TA
R(14) = N/tassets - P.equity_target;        % Equity as % of TA
R(15) = Y*P.Bbar*Bgcbbar/(4*Y) - P.CB_target;  % CB assets as % of GDP
R(16) = eta_DC - P.eta_DC;